// <auto-generated />
using CSharpAcademyBot.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpAcademyBot.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20230308143713_ModelNameChange")]
    partial class ModelNameChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSharpAcademyBot.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CSharpAcademyBot.Models.UserReputation", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserReputation");
                });

            modelBuilder.Entity("CSharpAcademyBot.Models.UserReputation", b =>
                {
                    b.HasOne("CSharpAcademyBot.Models.User", "User")
                        .WithOne("Reputation")
                        .HasForeignKey("CSharpAcademyBot.Models.UserReputation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSharpAcademyBot.Models.User", b =>
                {
                    b.Navigation("Reputation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
